set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html

Plugin 'tpope/vim-surround'

Plugin 'bling/vim-airline'

Plugin 'scrooloose/nerdtree'

Plugin 'scrooloose/nerdcommenter'

Plugin 'leafgarland/typescript-vim'

Plugin 'plasticboy/vim-markdown'

Plugin 'townk/vim-autoclose'

Plugin 'digitaltoad/vim-pug'

Plugin 'pangloss/vim-javascript'

Plugin 'bronson/vim-trailing-whitespace'

Plugin 'yggdroot/indentline'

Plugin 'styled-components/vim-styled-components'

Plugin 'mxw/vim-jsx'

Plugin 'kien/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ " Put your non-Plugin stuff after this line

" NERDTree settings
map <C-n> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" NERDcommenter settings
let mapleader=","
set timeout timeoutlen=1500
let g:NERDSpaceDelims = 1
let g:NERDTrimTrailingWhitespace = 1

" typescript-vim settings
" let g:typescript_indent_disable = 1

" tab spaces of 2, tabs as spaces
set tabstop=2
set expandtab
set softtabstop=2
set shiftwidth=2

set number
set relativenumber

set colorcolumn=80

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
